// Code generated by MockGen. DO NOT EDIT.
// Source: app/domain/services/user.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/hanifmhilmy/proj-dompet-api/app/domain/model"
	reflect "reflect"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// SaveCreatedUser mocks base method
func (m *MockUserServiceInterface) SaveCreatedUser(data model.SignUpDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCreatedUser", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCreatedUser indicates an expected call of SaveCreatedUser
func (mr *MockUserServiceInterfaceMockRecorder) SaveCreatedUser(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCreatedUser", reflect.TypeOf((*MockUserServiceInterface)(nil).SaveCreatedUser), data)
}
